[package]
name = "repr-viewer-wasm"
version = "0.1.0"
edition = "2024"
authors = ["akanevrc"]
license = "MIT"
description = "WebAssembly module for Number Representation Viewer"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.103"
